<?php

########################################################################
# Extension Manager/Repository config file for ext: "file"
#
# Auto generated by Extension Builder 2011-07-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'File handling',
	'description' => 'Extbase domain models for the DAM extension, Gallery views, List views, View helpers',
	'category' => 'plugin',
	'author' => 'Marco Huber',
	'author_email' => 'mail@marco-huber.de',
	'author_company' => '',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid,dam,static_info_tables,extbase_staticinfotables,view_helpers',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'dam' => '',
			'static_info_tables' => '',
			'extbase_staticinfotables' => '',
			'view_helpers' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>